/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BrowserLayoutRouteImport } from './routes/_browserLayout'
import { Route as BrowserLayoutSplatRouteImport } from './routes/_browserLayout/$'

const BrowserLayoutRoute = BrowserLayoutRouteImport.update({
  id: '/_browserLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowserLayoutSplatRoute = BrowserLayoutSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => BrowserLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof BrowserLayoutSplatRoute
}
export interface FileRoutesByTo {
  '/$': typeof BrowserLayoutSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_browserLayout': typeof BrowserLayoutRouteWithChildren
  '/_browserLayout/$': typeof BrowserLayoutSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/$'
  id: '__root__' | '/_browserLayout' | '/_browserLayout/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  BrowserLayoutRoute: typeof BrowserLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_browserLayout': {
      id: '/_browserLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof BrowserLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_browserLayout/$': {
      id: '/_browserLayout/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof BrowserLayoutSplatRouteImport
      parentRoute: typeof BrowserLayoutRoute
    }
  }
}

interface BrowserLayoutRouteChildren {
  BrowserLayoutSplatRoute: typeof BrowserLayoutSplatRoute
}

const BrowserLayoutRouteChildren: BrowserLayoutRouteChildren = {
  BrowserLayoutSplatRoute: BrowserLayoutSplatRoute,
}

const BrowserLayoutRouteWithChildren = BrowserLayoutRoute._addFileChildren(
  BrowserLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  BrowserLayoutRoute: BrowserLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
